version: '3.5'
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: qdrant
    ports:
      - "6333:6333"   # Qdrant REST API
      - "6334:6334"   # Qdrant gRPC
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data: 